from starlette.config import Config

config = Config(".env")

GOOGLE_CLIENT_ID = config("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = config("GOOGLE_CLIENT_SECRET")
KAKAO_REST_API_KEY = config("KAKAO_REST_API_KEY")
KAKAO_SECRET = config("KAKAO_SECRET")
NAVER_CLIENT_ID = config("NAVER_CLIENT_ID")
NAVER_CLIENT_SECRET = config("NAVER_CLIENT_SECRET")
SESSION_SECRET_KEY = config("SESSION_SECRET_KEY")
DB_URL = config("DB_URL")
