"""initial

Revision ID: 006308a9a5ff
Revises: 
Create Date: 2025-04-29 16:54:13.622937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '006308a9a5ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Homie_dongs',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('district', sa.String(length=4), nullable=False),
    sa.Column('dong', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Homie_questions',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('main_category', sa.String(length=10), nullable=False),
    sa.Column('sub_category', sa.String(length=10), nullable=False),
    sa.Column('content', sa.String(length=50), nullable=False),
    sa.Column('input_type', sa.Enum('select', 'radio', 'text', name='typeenum'), nullable=False),
    sa.Column('icon_path', sa.String(length=100), nullable=True),
    sa.Column('code', sa.SmallInteger(), nullable=False),
    sa.Column('state', sa.Enum('active', 'inactive', name='stateenum'), server_default=sa.text("'active'"), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('expired_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Seoul_dong_codes',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('gu_name', sa.String(length=10), nullable=False),
    sa.Column('dong_name', sa.String(length=10), nullable=False),
    sa.Column('short_code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('Seoul_rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dong_code', sa.String(length=20), nullable=True),
    sa.Column('gu_name', sa.String(length=20), nullable=True),
    sa.Column('dong_name', sa.String(length=20), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('room_type', sa.String(length=50), nullable=True),
    sa.Column('room_title', sa.String(length=255), nullable=True),
    sa.Column('room_desc', sa.TEXT(), nullable=True),
    sa.Column('price_type', sa.String(length=20), nullable=True),
    sa.Column('price_info', sa.String(length=50), nullable=True),
    sa.Column('img_url_list', sa.JSON(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('floor', sa.String(length=20), nullable=True),
    sa.Column('area_m2', sa.Float(), nullable=True),
    sa.Column('maintenance_fee', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Subway_stations',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('expired_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('state', sa.Enum('active', 'inactive', name='stateenum'), server_default=sa.text("'active'"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Homie_answers',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('homie_question_id', sa.SmallInteger(), nullable=False),
    sa.Column('content', sa.String(length=50), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=True),
    sa.Column('state', sa.Enum('active', 'inactive', name='stateenum'), server_default=sa.text("'active'"), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('expired_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['homie_question_id'], ['Homie_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Homie_dong_coefficients',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('homie_dong_id', sa.SmallInteger(), nullable=False),
    sa.Column('sub_category', sa.String(length=10), nullable=False),
    sa.Column('coefficient', sa.DECIMAL(precision=6, scale=5), nullable=False),
    sa.ForeignKeyConstraint(['homie_dong_id'], ['Homie_dongs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Homie_histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Homie_qna_histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('homie_history_id', sa.Integer(), nullable=False),
    sa.Column('homie_question_id', sa.SmallInteger(), nullable=False),
    sa.Column('homie_answer_id', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['homie_answer_id'], ['Homie_answers.id'], ),
    sa.ForeignKeyConstraint(['homie_history_id'], ['Homie_histories.id'], ),
    sa.ForeignKeyConstraint(['homie_question_id'], ['Homie_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Homie_qna_histories')
    op.drop_table('Homie_histories')
    op.drop_table('Homie_dong_coefficients')
    op.drop_table('Homie_answers')
    op.drop_table('Users')
    op.drop_table('Subway_stations')
    op.drop_table('Seoul_rooms')
    op.drop_table('Seoul_dong_codes')
    op.drop_table('Homie_questions')
    op.drop_table('Homie_dongs')
    # ### end Alembic commands ###
