"""Added created at in soulroom table

Revision ID: 2aba0ad75e24
Revises: 006308a9a5ff
Create Date: 2025-04-30 15:20:25.401787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aba0ad75e24'
down_revision: Union[str, None] = '006308a9a5ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Seoul_rooms', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Seoul_rooms', 'created_at')
    # ### end Alembic commands ###
