"""nullable score

Revision ID: 851ae84f3827
Revises: eb5840bae754
Create Date: 2025-04-24 11:43:38.881119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '851ae84f3827'
down_revision: Union[str, None] = 'eb5840bae754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Homie_answers', 'score',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               existing_nullable=True)
    op.add_column('Homie_questions', sa.Column('code', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Homie_questions', 'code')
    op.alter_column('Homie_answers', 'score',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
