"""create tables

Revision ID: eb5840bae754
Revises: 
Create Date: 2025-04-24 11:27:38.576169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eb5840bae754'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Homie_answers', 'score',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               nullable=False)
    op.add_column('Homie_questions', sa.Column('code', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Homie_questions', 'code')
    op.alter_column('Homie_answers', 'score',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               nullable=True)
    # ### end Alembic commands ###
